apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cilium-networking-poc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.31.0@sha256:06aa3d7be10bc6307990c81bdca075793132e9163391abc370c015e344e23128
          ports:
            - containerPort: 80
