apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cilium-networking-poc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.31.0@sha256:800e7c98538c6bf725f5177e841aa720ae0ed1c378bbea368b6330bfe18a36b3
          ports:
            - containerPort: 80
