apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cilium-networking-poc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.31.4@sha256:25ee11a13a12120be02c56b9606fde6ffeeb3dff002a9e072c4a2611ab5fd995
          ports:
            - containerPort: 80
