apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cilium-networking-poc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.4@sha256:9dd288848f4495869f76676e419ae2d767ca99fece2ec37ec0261f9fdaab5204
          ports:
            - containerPort: 80
