apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: cilium-networking-poc
  labels:
    app: nginx
  annotations:
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/sharing-key: "shared-ingress"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 6789
      protocol: TCP
      targetPort: 80
