apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: caddy
          image: caddy:2.10.0-alpine@sha256:ae4458638da8e1a91aafffb231c5f8778e964bca650c8a8cb23a7e8ac557aa3c
          ports:
            - containerPort: 80
          volumeMounts:
            - name: host-www
              mountPath: /srv
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
      securityContext: {}
      volumes:
        - name: host-www
          hostPath:
            path: /home/arska/www
        - name: caddyfile
          hostPath:
            path: /home/arska/k8s-Caddyfile
