apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: caddy
          image: caddy:2.10.2-alpine@sha256:a4180db0805b3725ddf936d2e6290553745c7339c003565da717ee612fd8a888
          ports:
            - containerPort: 80
          volumeMounts:
            - name: host-www
              mountPath: /srv
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
      securityContext: {}
      volumes:
        - name: host-www
          hostPath:
            path: /home/arska/www
        - name: caddyfile
          hostPath:
            path: /home/arska/k8s-Caddyfile
