apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: caddy
          image: caddy:2.11.4-alpine@sha256:de23def33b17fb5d1290b0f6c2add1d70780e52341896c00a4c8a2a2fe9d355e
          ports:
            - containerPort: 80
          volumeMounts:
            - name: host-www
              mountPath: /srv
            - name: caddy
              mountPath: /etc/caddy
      securityContext: {}
      volumes:
        - name: host-www
          nfs:
            server: 192.168.86.87
            path: /k8s/www
            readOnly: true
        - name: caddy
          nfs:
            server: 192.168.86.87
            path: /k8s/caddy
            readOnly: true
