apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: caddy
          image: caddy:2.11.4-alpine@sha256:6aeddd44c3078b0f9a35206472a11420648a79c184603ef95957d0a20044cb2b
          ports:
            - containerPort: 80
          volumeMounts:
            - name: host-www
              mountPath: /srv
            - name: caddy
              mountPath: /etc/caddy
      securityContext: {}
      volumes:
        - name: host-www
          nfs:
            server: 192.168.86.87
            path: /k8s/www
            readOnly: true
        - name: caddy
          nfs:
            server: 192.168.86.87
            path: /k8s/caddy
            readOnly: true
