apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: caddy
          image: caddy:2.10.2-alpine@sha256:4c6e91c6ed0e2fa03efd5b44747b625fec79bc9cd06ac5235a779726618e530d
          ports:
            - containerPort: 80
          volumeMounts:
            - name: host-www
              mountPath: /srv
            - name: caddy
              mountPath: /etc/caddy
      securityContext: {}
      volumes:
        - name: host-www
          nfs:
            server: 192.168.86.87
            path: /k8s/www
            readOnly: true
        - name: caddy
          nfs:
            server: 192.168.86.87
            path: /k8s/caddy
            readOnly: true
