apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: caddy
spec:
  secretName: tls-secret
  dnsNames:
    - sik75.aarnihalinen.fi
    - seitsemantahdenliike.fi
    - www.seitsemantahdenliike.fi
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io
