apiVersion: v1
kind: Service
metadata:
  name: caddy-svc
  namespace: caddy
  labels:
    app: caddy
spec:
  type: ClusterIP
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
