apiVersion: v1
kind: Service
metadata:
  name: icecast-svc
  namespace: icecast
  labels:
    app: icecast
spec:
  type: LoadBalancer
  selector:
    app: icecast
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
