apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tp-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: registry.gitlab.com/arskah/toiletpaper.rent/backend:latest@sha256:dbebcc49919e963964f33e9b6cbfe0f296a241375b84002ab906ad86c382282a
          env:
            - name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_DB
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8000
              name: http
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
          #   runAsUser: 1001
          #   runAsNonRoot: true
          #   seccompProfile:
          #     type: RuntimeDefault
          #   capabilities:
          #     drop:
          #       - ALL
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 1024Mi
