apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: tp-rent
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
