apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.17.3
      chart: cert-manager
      helm:
        releaseName: cert-manager
        version: v3
        valuesObject:
          installCRDs: true
          webhook:
            securePort: 10260
    - repoURL: https://github.com/Arskah/kube.git
      path: cert-manager
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
