apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.17.4
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valuesObject:
        operator:
          replicas: 1
        k8sServiceHost: kube.aarnihalinen.fi
        k8sServicePort: 6443
        kubeProxyReplacement: true
        ingressController:
          default: true
          enabled: true
          loadbalancerMode: shared
          service:
            type: LoadBalancer
            externalTrafficPolicy: "Local"
          hostNetwork:
            enabled: true
            sharedListenerPort: 9999
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
