apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.18.5
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valuesObject:
        ipam:
          mode: kubernetes
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              # - SYS_MODULE # Needs to be dropper per Talos docs
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              # - SYS_MODULE # Needs to be dropper per Talos docs
              - SYS_ADMIN
              - SYS_RESOURCE
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        k8sServiceHost: localhost
        k8sServicePort: 7445
        kubeProxyReplacement: true
        # k8sServiceHost: 192.168.86.73
        # k8sServicePort: 6443
        operator:
          replicas: 1
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
        ingressController:
          enabled: true
          loadbalancerMode: dedicated
          service:
            loadBalancerIP: 192.168.86.100
        l2announcements:
          enabled: true
        devices: eth0
        externalIPs:
          enabled: true
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
