apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: kube-system
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.14.*
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valueFiles:
        - values.yaml
      values: |
        kubeProxyReplacement: true
        k8sServiceHost:192.168.86.22
        k8sServicePort: 6443
        operator:
          replicas: 1
