apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.17.4
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valuesObject:
        operator:
          replicas: 1
        k8sServiceHost: kube.aarnihalinen.fi
        k8sServicePort: 6443
        kubeProxyReplacement: true
        ingressController:
          default: true
          enabled: true
          loadbalancerMode: shared
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-lb-ipam
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.86.22"
      stop: "192.168.86.22"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-lb-all-services
  namespace: kube-system
spec:
  interfaces:
    - enp37s0
  externalIPs: true
  loadBalancerIPs: true
