apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.18.2
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valuesObject:
        kubeProxyReplacement: true
        k8sServiceHost: 192.168.86.22
        k8sServicePort: 6443
        operator:
          replicas: 1
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
        ingressController:
          enabled: true
          loadbalancerMode: dedicated
          service:
            loadBalancerIP: 192.168.86.100
        l2announcements:
          enabled: true
        devices: enp37s0
        externalIPs:
          enabled: true
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
