apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  destination:
    namespace: docker-registry
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/Arskah/kube.git
      path: docker-registry
      targetRevision: HEAD
    - repoURL: https://helm.twun.io
      targetRevision: 2.2.*
      chart: docker-registry
      helm:
        releaseName: docker-registry
        version: v3
        valueFiles:
          - values.yaml
        valuesObject:
          persistence:
            enabled: true
            size: 10Gi
            deleteEnabled: true
            existingClaim: docker-registry-pv-claim
          secrets:
            htpasswd: arskah:$2y$05$ZMDZy776w/RfPy3MmaHbWucMBNEUo/CgCzgKt2jeWTfQJGdcIc0dO
          ingress:
            enabled: true
            className: nginx
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
            path: /
            hosts:
              - registry.aarnihalinen.fi
            tls:
              - secretName: docker-registry-tls
                hosts:
                  - registry.aarnihalinen.fi
