apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
  project: applications
  source:
    repoURL: https://charts.gitlab.io
    targetRevision: 0.81.0
    chart: gitlab-runner
    helm:
      releaseName: gitlab-runner
      version: v3
      valuesObject:
        gitlabUrl: https://gitlab.com
        runners:
          privileged: false
          namespace: gitlab-runner
          secret: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
