apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd-image-updater.argoproj.io/image-list: image=registry.aarnihalinen.fi/aarnihalinen.fi:latest
    argocd-image-updater.argoproj.io/image.update-strategy: digest
    argocd-image-updater.argoproj.io/image.pull-secret: pullsecret:argocd/regcred
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: k8s/prod
    repoURL: https://github.com/Arskah/homepage.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
