apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-staging
  namespace: argocd
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/prod
    repoURL: https://github.com/Arskah/homepage.git
    targetRevision: HEAD
