apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd-image-updater.argoproj.io/image-list: image=registry.aarnihalinen.fi/homepage:next
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image.kustomize.image-name: homepage # Needed for fixing the source type Directory issue?
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/image.pull-secret: pullsecret:argocd/regcred-argocd
    argocd-image-updater.argoproj.io/image.update-strategy: digest
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: k8s/staging
    repoURL: https://github.com/Arskah/homepage.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
