apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-production
  namespace: argocd
spec:
  destination:
    namespace: homepage-production
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: homepage-production
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
