apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: production-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: "semver"
    forceUpdate: false
    allowTags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    ignoreTags: ["latest", "dev", "test", "next"]
    pullSecret: pullsecret:argocd/regcred-argocd
  writeBackConfig:
    method: "argocd"
  applicationRefs:
    - namePattern: "homepage-staging"
      commonUpdateSettings:
        updateStrategy: digest
        forceUpdate: true
        allowTags: "next"
        ignoreTags: ["latest"]
      images:
        - alias: "image"
          imageName: "registry.aarnihalinen.fi/homepage:next"
    - namePattern: "homepage-production"
      commonUpdateSettings:
        updateStrategy: digest
        forceUpdate: true
        allowTags: "latest"
        ignoreTags: ["next"]
      images:
        - alias: "production"
          imageName: "registry.aarnihalinen.fi/homepage:latest"
