apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.*
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      version: v3
      parameters:
        - name: controller.service.externalIPs
          value: |
            [ 192.168.1.22 ]
        - name: controller.service.nodePorts.http
          value: "30080"
        - name: controller.service.nodePorts.https
          value: "30443"
        - name: controller.service.type
          value: NodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
