# Define an IP pool for Cilium to use for LoadBalancer IPs.
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: general-pool
spec:
  blocks:
    - start: "192.168.86.100"
      stop: "192.168.86.255"
---
# Define an L2 Announcement Policy named "policy1".
# This policy enables L2 announcements for all interfaces matching the pattern 'eth[0-9]+'.
# It includes both externalIPs and loadBalancerIPs in the announcements
# (important for discoverability in our home lab).
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  interfaces:
    - enp37s0
  externalIPs: true
  loadBalancerIPs: true
