apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.0.0
    chart: kube-prometheus-stack
    helm:
      releaseName: monitoring
      version: v3
      skipCrds: false
      valuesObject:
        prometheusOperator:
          admissionWebhooks:
            certManager:
              enabled: true
            patch:
              enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - PruneLast=true
      - Replace=true
