apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.8.1
    chart: kube-prometheus-stack
    helm:
      releaseName: monitoring
      version: v3
      skipCrds: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
