apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-library
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: music-library
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: k8s
    repoURL: https://github.com/Arskah/music-library.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
