apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: infra
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.18.1
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets
        version: v3
        valuesObject:
          fullnameOverride: sealed-secrets-controller
    - repoURL: https://github.com/Arskah/kube.git
      path: sealed-secrets
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
