apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-tls
  namespace: docker-registry
spec:
  secretName: docker-registry-tls
  dnsNames:
    - registry.aarnihalinen.fi
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io
