apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: tp-rent
spec:
  secretName: tls-secret
  dnsNames:
    - tp.aarnihalinen.fi
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
