apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: tp-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: db
          image: postgres:12@sha256:8c0ab130932452c9a9dd97237e55101cee61a51d5f499a6bdeb4106e392554a3
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pvc
              mountPath: /var/lib/postgresql/data
              subPath: db
              readOnly: false
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
          #   runAsUser: 1001
          #   runAsNonRoot: true
          #   seccompProfile:
          #     type: RuntimeDefault
          #   capabilities:
          #     drop:
          #       - ALL
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 1024Mi
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: db-pvc
