apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: tp-rent
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
