apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: tp-rent
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
