apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: tp-rent
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
